### ISSUE TITLE
New Documentation Checklist

### ISSUE THREAD

**Issue by awatson1978** [awatson1978/starrynight#57]
The new documentation is going to be heavily inspired by the [Nightwatchjs.org](http://Nightwatchjs.org) website.  
- [x] USAGE
- [x] QUICKSTART
- [x] ARCHITECTURE
- [x] TUTORIAL
- [ ] Overview
  - [x] Validation vs Verification Testing
  - [x] Adding Nightwatch to Your App
  - [ ] Running Frameworks
- [ ] Basic Validation Testing
  - [x] App Surface Coverage
  - [ ] Component Surface Coverage
  - [x] Testing Component Output
  - [x] Testing Component User Input
  - [ ] Generating Design Documentation (BDD)
- [ ] Business Validation Testing (Intermediate)
  - [ ] Behavior Driven Development
  - [ ] System Specification Documents
- [ ] Isomorphic Validation Testing (Advanced)
  - [ ] Configuration Autogeneration
  - [ ] Running Validation Tests Across Both Packages and Apps
  - [ ] Package Validation and Verification Testing
  - [ ] Integration Testing Between a Packages
  - [ ] Package Only Apps
- [ ] Basic Verification Testing
  - [ ] Client-Side Unit Tests
  - [ ] Server-Side Unit Tests
- [ ] Isomorphic Verification Testing
  - [ ] Running Verification Tests Across Both Packages and Apps
  - [ ] Server, Client, and Package Verification Testing
  - [ ] Package Only Apps
- [ ] Miscellaneous
  - [ ] Testing URLs
  - [ ] Testing Meteor Methods
  - [ ] Multi-Window PingPong Testing
- [x] EXAMPLES
- [ ] API
- [x] FAQ
- [ ] INSTALLATION
  - [ ] Prerequisites
  - [ ] Windows

**Comment by awatson1978** [comment]
Beta version of documentation is available at starrynight-beta.meteor.com
